// <auto-generated />
using System;
using FleetDelivery.Modules.Shipments.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetDelivery.Modules.Shipments.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShipmentsDbContext))]
    [Migration("20260908163420_AddProofOfDeliveryPhotos")]
    partial class AddProofOfDeliveryPhotos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shipments")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetDelivery.BuildingBlocks.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("NextAttemptOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_on");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOn", "NextAttemptOn")
                        .HasDatabaseName("ix_outbox_messages_unprocessed")
                        .HasFilter("processed_on IS NULL");

                    b.ToTable("outbox_messages", "shipments");
                });

            modelBuilder.Entity("FleetDelivery.Modules.Shipments.Domain.ProofOfDeliveryPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.ToTable("proof_of_delivery_photos", "shipments");
                });

            modelBuilder.Entity("FleetDelivery.Modules.Shipments.Domain.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedDriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_driver_id");

                    b.Property<Guid?>("AssignedVehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_vehicle_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("HasProofOfDelivery")
                        .HasColumnType("boolean")
                        .HasColumnName("has_proof_of_delivery");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("recipient_phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tracking_number");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TrackingNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_shipments_tracking_number");

                    b.ToTable("shipments", "shipments");
                });

            modelBuilder.Entity("FleetDelivery.Modules.Shipments.Domain.ProofOfDeliveryPhoto", b =>
                {
                    b.HasOne("FleetDelivery.Modules.Shipments.Domain.Shipment", null)
                        .WithOne()
                        .HasForeignKey("FleetDelivery.Modules.Shipments.Domain.ProofOfDeliveryPhoto", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetDelivery.Modules.Shipments.Domain.Shipment", b =>
                {
                    b.OwnsMany("FleetDelivery.Modules.Shipments.Domain.DeliveryAttempt", "DeliveryAttempts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("AttemptedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("attempted_at");

                            b1.Property<Guid>("DriverId")
                                .HasColumnType("uuid")
                                .HasColumnName("driver_id");

                            b1.Property<string>("Notes")
                                .HasColumnType("text")
                                .HasColumnName("notes");

                            b1.Property<string>("Outcome")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("outcome");

                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("shipment_id");

                            b1.HasKey("Id");

                            b1.HasIndex("ShipmentId")
                                .HasDatabaseName("ix_delivery_attempts_shipment_id");

                            b1.ToTable("delivery_attempts", "shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("FleetDelivery.Modules.Shipments.Domain.Address", "DestinationAddress", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("destination_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("destination_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("destination_postal_code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("destination_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("destination_street");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("shipments", "shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("FleetDelivery.Modules.Shipments.Domain.Address", "OriginAddress", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("origin_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("origin_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("origin_postal_code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("origin_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("origin_street");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("shipments", "shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsMany("FleetDelivery.Modules.Shipments.Domain.TrackingEvent", "TrackingEvents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("ActorUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("actor_user_id");

                            b1.Property<string>("Notes")
                                .HasColumnType("text")
                                .HasColumnName("notes");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("occurred_at");

                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("shipment_id");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("type");

                            b1.HasKey("Id");

                            b1.HasIndex("ShipmentId")
                                .HasDatabaseName("ix_tracking_events_shipment_id");

                            b1.ToTable("tracking_events", "shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.Navigation("DeliveryAttempts");

                    b.Navigation("DestinationAddress")
                        .IsRequired();

                    b.Navigation("OriginAddress")
                        .IsRequired();

                    b.Navigation("TrackingEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
